### ISSUE TITLE
Restore Repo's readme file from February

### ISSUE THREAD

**Issue by coriobriensfdo** [SFDO-Community-Sprints/PMM-V4S#3]
It would appear that the readme was overwritten in error when @ryanbaba was making some changes to configure for CCI. Ryan, and chance you see the path to restore the latest updates from February? If it's not obvious I can ask for some help on my end, but it's not something I've had to do before. 

FYI @DatabaseDeanne @sprieto37

**Comment by DatabaseDeanne** [comment]
Thanks @coriobriensfdo. I have combined the previous readme information with the information that @ryanbaba added and updated the current readme.

FYI @sprieto37
